# 1. Dependencias

FROM node:22-alpine AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install --production=false

# 2. Build

FROM node:22-alpine AS build

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

# Build the project
RUN npm run build

# Install production deps only (clean)
RUN npm prune --production && npm cache clean --force

# 3. Prod

FROM node:22-alpine AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

EXPOSE 3004

CMD ["node", "dist/main.js"]
